import Head from "next/head";
import Navbar from "../ui/Navbar";

interface Props {
  title?: string;
  children: React.ReactNode;
}

export default function Layout({ title = "Portafolio", children }: Props) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/icon.svg" />
      </Head>
      <div>
        <Navbar />
        {children}
      </div>
    </>
  );
}
